/**
 * F2.1 — Planned Orders Panel
 *
 * Displays time-phased order recommendations generated by the Order Recommendation Engine.
 * Shows KPI cards, filterable table, approve/reject workflow.
 */

import React, { useState, useRef, useEffect } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  queryKeys,
  fetchPlannedOrders,
  fetchPlannedOrdersSummary,
  approvePlannedOrder,
  rejectPlannedOrder,
  generatePlannedOrders,
  STALE,
} from "@/api/queries";
import type { PlannedOrder } from "@/api/queries";
import { CheckSquare, ChevronDown, ChevronRight } from "lucide-react";
import { EmptyState } from "@/components/EmptyState";
import { useGlobalFilterContext } from "@/context/GlobalFilterContext";

function formatCurrency(v: number | null): string {
  if (v == null) return "—";
  if (v >= 1_000_000) return `$${(v / 1_000_000).toFixed(2)}M`;
  if (v >= 1_000) return `$${(v / 1_000).toFixed(1)}K`;
  return `$${v.toFixed(2)}`;
}

function formatDate(s: string | null): string {
  if (!s) return "—";
  const d = new Date(s + "T00:00:00");
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function confidenceLabel(score: number | null): { label: string; cls: string } {
  if (score == null) return { label: "—", cls: "text-muted-foreground" };
  if (score >= 0.8) return { label: `${(score * 100).toFixed(0)}% HIGH`, cls: "text-emerald-600 dark:text-emerald-400" };
  if (score >= 0.5) return { label: `${(score * 100).toFixed(0)}% MED`, cls: "text-amber-600 dark:text-amber-400" };
  return { label: `${(score * 100).toFixed(0)}% LOW`, cls: "text-red-600 dark:text-red-400" };
}

function getTriggerExplanation(order: PlannedOrder): string {
  switch (order.trigger_reason) {
    case "below_rop":
      return `Projected inventory falls below the reorder point (${(order.reorder_point ?? 0).toLocaleString()}) within the lead time window of ${order.lead_time_days} days.`;
    case "below_ss":
      return `Safety stock coverage is at risk. Current on-hand (${(order.current_qty_on_hand ?? 0).toLocaleString()}) will not cover demand during lead time.`;
    case "stockout":
      return "A stockout is imminent or has already occurred. Urgent replenishment required.";
    case "scheduled":
      return "Regularly scheduled replenishment based on the planning cycle.";
    default:
      return order.trigger_reason.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  }
}

function OrderDetailCard({
  order,
  onApprove,
  onReject,
  approvePending,
}: {
  order: PlannedOrder;
  onApprove: (id: number) => void;
  onReject: (id: number) => void;
  approvePending: boolean;
}) {
  const conf = confidenceLabel(order.confidence_score);
  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
      {/* Column 1: Order details */}
      <div className="space-y-1.5">
        <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Order Details</p>
        <p className="text-sm font-medium">{order.item_id} @ {order.loc}</p>
        <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-xs">
          <span className="text-muted-foreground">Recommended Qty</span>
          <span className="font-medium">{order.recommended_qty?.toLocaleString() ?? "--"}</span>
          <span className="text-muted-foreground">Net Requirement</span>
          <span className="font-medium">{order.net_requirement_qty?.toLocaleString() ?? "--"}</span>
          <span className="text-muted-foreground">MOQ</span>
          <span className="font-medium">{order.moq?.toLocaleString() ?? "--"}</span>
          <span className="text-muted-foreground">Supplier</span>
          <span className="font-medium">{order.supplier_name ?? order.supplier_id ?? "--"}</span>
          <span className="text-muted-foreground">Unit Cost</span>
          <span className="font-medium">{order.unit_cost != null ? formatCurrency(order.unit_cost) : "--"}</span>
          <span className="text-muted-foreground">Order Value</span>
          <span className="font-medium">{order.order_value != null ? formatCurrency(order.order_value) : "--"}</span>
          <span className="text-muted-foreground">Lead Time</span>
          <span className="font-medium">{order.lead_time_days}d</span>
          <span className="text-muted-foreground">Order By</span>
          <span className={`font-medium ${order.is_past_due ? "text-red-600 dark:text-red-400" : ""}`}>
            {formatDate(order.order_by_date)}{order.is_past_due ? " (PAST DUE)" : ""}
          </span>
          <span className="text-muted-foreground">Expected Receipt</span>
          <span className="font-medium">{formatDate(order.expected_receipt_date)}</span>
        </div>
      </div>

      {/* Column 2: Current position & confidence */}
      <div className="space-y-1.5">
        <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Current Position</p>
        <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-xs">
          <span className="text-muted-foreground">On Hand</span>
          <span className="font-medium">{order.current_qty_on_hand?.toLocaleString() ?? "--"}</span>
          <span className="text-muted-foreground">Safety Stock</span>
          <span className="font-medium">{order.safety_stock?.toLocaleString() ?? "--"}</span>
          <span className="text-muted-foreground">Reorder Point</span>
          <span className="font-medium">{order.reorder_point?.toLocaleString() ?? "--"}</span>
          <span className="text-muted-foreground">Inbound Qty</span>
          <span className="font-medium">{order.confirmed_inbound_qty?.toLocaleString() ?? "--"}</span>
          <span className="text-muted-foreground">LT Forecast Demand</span>
          <span className="font-medium">{order.lt_forecast_demand?.toLocaleString() ?? "--"}</span>
        </div>

        {/* Confidence breakdown */}
        <div className="mt-3 rounded border px-2 py-1.5 bg-background">
          <div className="flex items-center gap-2 mb-1">
            <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Confidence</p>
            <span className={`text-xs font-medium ${conf.cls}`}>{conf.label}</span>
          </div>
          {order.confidence_reason && (
            <p className="text-[10px] text-muted-foreground leading-relaxed">{order.confidence_reason}</p>
          )}
        </div>

        {/* Trigger reason */}
        <div className="mt-2">
          <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Trigger Reason</p>
          <p className="text-xs text-muted-foreground leading-relaxed mt-0.5">
            {getTriggerExplanation(order)}
          </p>
        </div>
      </div>

      {/* Column 3: Actions */}
      <div className="space-y-2">
        <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Quick Actions</p>
        {order.status === "proposed" && (
          <>
            <button
              onClick={(e) => { e.stopPropagation(); onApprove(order.id); }}
              disabled={approvePending}
              className="w-full px-3 py-1.5 text-xs font-medium rounded border border-emerald-300 text-emerald-700 hover:bg-emerald-50 dark:border-emerald-700 dark:text-emerald-400 dark:hover:bg-emerald-900/20 transition-colors disabled:opacity-50"
            >
              Approve Order
            </button>
            <button
              onClick={(e) => { e.stopPropagation(); onReject(order.id); }}
              className="w-full px-3 py-1.5 text-xs font-medium rounded border border-red-300 text-red-700 hover:bg-red-50 dark:border-red-700 dark:text-red-400 dark:hover:bg-red-900/20 transition-colors"
            >
              Reject Order
            </button>
          </>
        )}
        <button className="w-full px-3 py-1.5 text-xs font-medium rounded border border-slate-300 text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-400 dark:hover:bg-slate-900/20 transition-colors">
          View Inventory Projection
        </button>
        <button className="w-full px-3 py-1.5 text-xs font-medium rounded border border-slate-300 text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-400 dark:hover:bg-slate-900/20 transition-colors">
          Edit Quantity
        </button>
      </div>
    </div>
  );
}

export function PlannedOrdersPanel() {
  const { filters: globalFilters } = useGlobalFilterContext();
  const qc = useQueryClient();
  const [itemFilter, setItemFilter] = useState("");
  const [locFilter, setLocFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("proposed,approved");
  const [pastDueOnly, setPastDueOnly] = useState(false);
  const [rejectModalId, setRejectModalId] = useState<number | null>(null);
  const [rejectReason, setRejectReason] = useState("");
  const [expandedOrderId, setExpandedOrderId] = useState<number | null>(null);

  const syncedGlobalRef = useRef<string>("");
  useEffect(() => {
    const key = `${globalFilters.item.join(",")}_${globalFilters.location.join(",")}`;
    if (key === syncedGlobalRef.current) return;
    syncedGlobalRef.current = key;
    if (globalFilters.item.length === 1) setItemFilter(globalFilters.item[0]);
    if (globalFilters.location.length === 1) setLocFilter(globalFilters.location[0]);
  }, [globalFilters.item, globalFilters.location]);

  const summaryQ = useQuery({
    queryKey: queryKeys.plannedOrdersSummary(),
    queryFn: fetchPlannedOrdersSummary,
    staleTime: STALE.TWO_MIN,
  });

  const ordersQ = useQuery({
    queryKey: queryKeys.plannedOrders({
      item_id: itemFilter,
      loc: locFilter,
      status: statusFilter,
      past_due_only: pastDueOnly,
    }),
    queryFn: () => fetchPlannedOrders({
      item_id: itemFilter || undefined,
      loc: locFilter || undefined,
      status: statusFilter,
      past_due_only: pastDueOnly,
    }),
    staleTime: STALE.ONE_MIN,
  });

  const approveMutation = useMutation({
    mutationFn: ({ id, approvedBy }: { id: number; approvedBy: string }) =>
      approvePlannedOrder(id, approvedBy),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["planned-orders"] });
      qc.invalidateQueries({ queryKey: ["planned-orders-summary"] });
    },
  });

  const rejectMutation = useMutation({
    mutationFn: ({ id, reason }: { id: number; reason: string }) =>
      rejectPlannedOrder(id, reason),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["planned-orders"] });
      qc.invalidateQueries({ queryKey: ["planned-orders-summary"] });
      setRejectModalId(null);
      setRejectReason("");
    },
  });

  const generateMutation = useMutation({
    mutationFn: () => generatePlannedOrders(),
    onSuccess: () => {
      setTimeout(() => {
        qc.invalidateQueries({ queryKey: ["planned-orders"] });
        qc.invalidateQueries({ queryKey: ["planned-orders-summary"] });
      }, 3000);
    },
  });

  const summary = summaryQ.data;
  const orders = ordersQ.data;

  return (
    <div className="space-y-4">
      {/* Info Banner */}
      <div className="text-xs text-amber-700 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded px-3 py-2 mb-3">
        <span className="font-semibold">ℹ System-generated proposals</span> — these are NOT purchase orders placed with suppliers. Approve = ready for release to procurement. See <strong>Open POs</strong> panel for orders already in transit.
      </div>

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-semibold text-base">Planned Orders</h3>
          <p className="text-xs text-muted-foreground mt-0.5">
            Time-phased order recommendations from the MRP engine.{" "}
            {summary?.generated_at && (
              <span>Last generated: {new Date(summary.generated_at).toLocaleString()}</span>
            )}
          </p>
        </div>
        <button
          onClick={() => generateMutation.mutate()}
          disabled={generateMutation.isPending}
          className="rounded-md bg-primary px-3 py-1.5 text-xs text-primary-foreground font-medium hover:bg-primary/90 disabled:opacity-50"
        >
          {generateMutation.isPending ? "Generating..." : "Generate"}
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          {
            label: "Proposed",
            value: summary?.status_counts?.proposed?.toLocaleString() ?? "—",
            sub: formatCurrency(summary?.total_proposed_value_usd ?? null),
            warn: false,
          },
          {
            label: "Past Due",
            value: summary?.past_due_proposed_count?.toLocaleString() ?? "—",
            sub: "need action",
            warn: (summary?.past_due_proposed_count ?? 0) > 0,
          },
          {
            label: "Approved",
            value: summary?.status_counts?.approved?.toLocaleString() ?? "—",
            sub: formatCurrency(summary?.total_approved_value_usd ?? null),
            warn: false,
          },
          {
            label: "Low Confidence",
            value: summary?.low_confidence_count?.toLocaleString() ?? "—",
            sub: `avg ${summary?.avg_confidence_score != null ? (summary.avg_confidence_score * 100).toFixed(0) + "%" : "—"}`,
            warn: (summary?.low_confidence_count ?? 0) > 0,
          },
        ].map((kpi) => (
          <div
            key={kpi.label}
            className={`rounded-lg border p-3 ${kpi.warn ? "border-amber-400/50 bg-amber-50/50 dark:bg-amber-900/10" : "bg-card"}`}
          >
            <p className="text-xs text-muted-foreground">{kpi.label}</p>
            <p className={`text-xl font-semibold mt-1 ${kpi.warn ? "text-amber-600 dark:text-amber-400" : ""}`}>
              {kpi.value}
            </p>
            <p className="text-xs text-muted-foreground mt-0.5">{kpi.sub}</p>
          </div>
        ))}
      </div>

      {/* Confidence Score Legend */}
      <div className="text-xs text-muted-foreground p-2 rounded bg-muted/30 border">
        <span className="font-medium text-foreground">Confidence Score: </span>
        <span className="text-green-600">● High ≥ 0.8</span> · <span className="text-amber-600">● Medium 0.5–0.79</span> · <span className="text-red-600">● Low &lt; 0.5</span>
        <span className="ml-2 text-muted-foreground">— Based on forecast accuracy + lead time stability</span>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-2 items-center">
        <input
          className="rounded-md border bg-background px-2 py-1 text-xs w-32"
          placeholder="Item No"
          value={itemFilter}
          onChange={(e) => setItemFilter(e.target.value)}
        />
        <input
          className="rounded-md border bg-background px-2 py-1 text-xs w-32"
          placeholder="Location"
          value={locFilter}
          onChange={(e) => setLocFilter(e.target.value)}
        />
        <select
          className="rounded-md border bg-background px-2 py-1 text-xs"
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
        >
          <option value="proposed,approved">Proposed + Approved</option>
          <option value="proposed">Proposed only</option>
          <option value="approved">Approved only</option>
          <option value="released">Released</option>
          <option value="rejected,cancelled">Rejected / Cancelled</option>
        </select>
        <label className="flex items-center gap-1 text-xs text-muted-foreground">
          <input
            type="checkbox"
            checked={pastDueOnly}
            onChange={(e) => setPastDueOnly(e.target.checked)}
          />
          Past-Due Only
        </label>
      </div>

      {/* Orders Table */}
      {ordersQ.isLoading ? (
        <div className="text-xs text-muted-foreground py-4 text-center">Loading...</div>
      ) : ordersQ.isError ? (
        <div className="text-xs text-red-600 py-4 text-center">Failed to load planned orders.</div>
      ) : !orders?.items?.length ? (
        <EmptyState
          icon={CheckSquare}
          title="No planned orders generated"
          description="Planned orders are system-generated replenishment proposals created when projected inventory falls below the reorder point within the lead time window. Each order has a confidence score based on data quality and recommends a quantity based on EOQ."
          steps={[
            { label: "Generate production forecasts first", command: "make forecast-generate" },
            { label: "Compute replenishment plan", command: "make replen-plan-compute" },
            { label: "Generate planned orders", command: "make planned-orders-generate" },
          ]}
        />
      ) : (
        <div className="rounded-lg border overflow-auto">
          <table className="w-full text-xs">
            <thead className="bg-muted/50">
              <tr>
                {[
                  { label: "" },
                  { label: "Item" },
                  { label: "Loc" },
                  { label: "Supplier" },
                  { label: "Rec. Qty" },
                  { label: "Value" },
                  { label: "Order By", title: "Latest date to place this order to meet projected demand. Missing this date puts you at stockout risk." },
                  { label: "LT", title: "Lead time in days from order placement to receipt." },
                  { label: "Confidence" },
                  { label: "Status" },
                  { label: "Actions" },
                ].map((h) => (
                  <th key={h.label} title={h.title} className="px-3 py-2 text-left font-medium text-muted-foreground whitespace-nowrap">
                    {h.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y">
              {orders.items.map((order: PlannedOrder) => {
                const conf = confidenceLabel(order.confidence_score);
                const isPastDue = order.is_past_due;
                const isExpanded = expandedOrderId === order.id;
                return (
                  <React.Fragment key={order.id}>
                  <tr
                    className={`cursor-pointer hover:bg-muted/30 ${isPastDue ? "bg-red-50/30 dark:bg-red-900/10" : ""} ${isExpanded ? "ring-1 ring-inset ring-primary/30" : ""}`}
                    onClick={() => setExpandedOrderId(isExpanded ? null : order.id)}
                  >
                    <td className="px-3 py-2 w-6">
                      {isExpanded ? (
                        <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
                      ) : (
                        <ChevronRight className="h-3.5 w-3.5 text-muted-foreground" />
                      )}
                    </td>
                    <td className="px-3 py-2 font-mono">{order.item_id}</td>
                    <td className="px-3 py-2">{order.loc}</td>
                    <td className="px-3 py-2 text-muted-foreground">
                      {order.supplier_name ?? order.supplier_id ?? "—"}
                    </td>
                    <td className="px-3 py-2 font-semibold">{order.recommended_qty?.toLocaleString()}</td>
                    <td className="px-3 py-2">{formatCurrency(order.order_value)}</td>
                    <td className={`px-3 py-2 whitespace-nowrap ${isPastDue ? "text-red-600 dark:text-red-400 font-semibold" : ""}`}>
                      {formatDate(order.order_by_date)}
                      {isPastDue && " ⚠"}
                    </td>
                    <td className="px-3 py-2">{order.lead_time_days}d</td>
                    <td className={`px-3 py-2 ${conf.cls}`}>{conf.label}</td>
                    <td className="px-3 py-2">
                      <span className={`inline-block rounded-full px-2 py-0.5 text-xs font-medium ${
                        order.status === "proposed" ? "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300"
                        : order.status === "approved" ? "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300"
                        : order.status === "released" ? "bg-cyan-100 text-cyan-700"
                        : "bg-muted text-muted-foreground"
                      }`}>
                        {order.status}
                      </span>
                    </td>
                    <td className="px-3 py-2">
                      {order.status === "proposed" && (
                        <div className="flex gap-1">
                          <button
                            onClick={(e) => { e.stopPropagation(); approveMutation.mutate({ id: order.id, approvedBy: "planner" }); }}
                            disabled={approveMutation.isPending}
                            className="rounded bg-emerald-600 px-2 py-0.5 text-white text-xs hover:bg-emerald-700 disabled:opacity-50"
                          >
                            Approve
                          </button>
                          <button
                            onClick={(e) => { e.stopPropagation(); setRejectModalId(order.id); setRejectReason(""); }}
                            className="rounded bg-red-600 px-2 py-0.5 text-white text-xs hover:bg-red-700"
                          >
                            Reject
                          </button>
                        </div>
                      )}
                    </td>
                  </tr>
                  {/* Inline drill-down expansion */}
                  {isExpanded && (
                    <tr className="border-t">
                      <td colSpan={11} className="bg-muted/30 px-4 py-4">
                        <OrderDetailCard
                          order={order}
                          onApprove={(id) => approveMutation.mutate({ id, approvedBy: "planner" })}
                          onReject={(id) => { setRejectModalId(id); setRejectReason(""); }}
                          approvePending={approveMutation.isPending}
                        />
                      </td>
                    </tr>
                  )}
                  </React.Fragment>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Reject Modal */}
      {rejectModalId !== null && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="bg-card rounded-lg border p-4 shadow-lg w-80">
            <h4 className="font-semibold text-sm mb-2">Reject Order #{rejectModalId}</h4>
            <textarea
              className="w-full rounded border bg-background p-2 text-xs h-20 resize-none"
              placeholder="Rejection reason (required)"
              value={rejectReason}
              onChange={(e) => setRejectReason(e.target.value)}
            />
            <div className="flex gap-2 mt-3 justify-end">
              <button
                onClick={() => setRejectModalId(null)}
                className="rounded border px-3 py-1 text-xs hover:bg-muted"
              >
                Cancel
              </button>
              <button
                onClick={() => rejectMutation.mutate({ id: rejectModalId!, reason: rejectReason })}
                disabled={!rejectReason.trim() || rejectMutation.isPending}
                className="rounded bg-red-600 px-3 py-1 text-xs text-white hover:bg-red-700 disabled:opacity-50"
              >
                Confirm Reject
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
