/**
 * F2.1 — Planned Orders Panel
 *
 * Displays time-phased order recommendations generated by the Order Recommendation Engine.
 * Shows KPI cards, filterable table, approve/reject workflow.
 */

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import {
  queryKeys,
  fetchPlannedOrders,
  fetchPlannedOrdersSummary,
  approvePlannedOrder,
  rejectPlannedOrder,
  generatePlannedOrders,
  STALE,
} from "@/api/queries";
import type { PlannedOrder } from "@/api/queries";
import { CheckSquare } from "lucide-react";
import { EmptyState } from "@/components/EmptyState";

function formatCurrency(v: number | null): string {
  if (v == null) return "—";
  if (v >= 1_000_000) return `$${(v / 1_000_000).toFixed(2)}M`;
  if (v >= 1_000) return `$${(v / 1_000).toFixed(1)}K`;
  return `$${v.toFixed(2)}`;
}

function formatDate(s: string | null): string {
  if (!s) return "—";
  const d = new Date(s + "T00:00:00");
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function confidenceLabel(score: number | null): { label: string; cls: string } {
  if (score == null) return { label: "—", cls: "text-muted-foreground" };
  if (score >= 0.8) return { label: `${(score * 100).toFixed(0)}% HIGH`, cls: "text-emerald-600 dark:text-emerald-400" };
  if (score >= 0.5) return { label: `${(score * 100).toFixed(0)}% MED`, cls: "text-amber-600 dark:text-amber-400" };
  return { label: `${(score * 100).toFixed(0)}% LOW`, cls: "text-red-600 dark:text-red-400" };
}

export function PlannedOrdersPanel() {
  const qc = useQueryClient();
  const [itemFilter, setItemFilter] = useState("");
  const [locFilter, setLocFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("proposed,approved");
  const [pastDueOnly, setPastDueOnly] = useState(false);
  const [rejectModalId, setRejectModalId] = useState<number | null>(null);
  const [rejectReason, setRejectReason] = useState("");

  const summaryQ = useQuery({
    queryKey: queryKeys.plannedOrdersSummary(),
    queryFn: fetchPlannedOrdersSummary,
    staleTime: STALE.TWO_MIN,
  });

  const ordersQ = useQuery({
    queryKey: queryKeys.plannedOrders({
      item_no: itemFilter,
      loc: locFilter,
      status: statusFilter,
      past_due_only: pastDueOnly,
    }),
    queryFn: () => fetchPlannedOrders({
      item_no: itemFilter || undefined,
      loc: locFilter || undefined,
      status: statusFilter,
      past_due_only: pastDueOnly,
    }),
    staleTime: STALE.ONE_MIN,
  });

  const approveMutation = useMutation({
    mutationFn: ({ id, approvedBy }: { id: number; approvedBy: string }) =>
      approvePlannedOrder(id, approvedBy),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["planned-orders"] });
      qc.invalidateQueries({ queryKey: ["planned-orders-summary"] });
    },
  });

  const rejectMutation = useMutation({
    mutationFn: ({ id, reason }: { id: number; reason: string }) =>
      rejectPlannedOrder(id, reason),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["planned-orders"] });
      qc.invalidateQueries({ queryKey: ["planned-orders-summary"] });
      setRejectModalId(null);
      setRejectReason("");
    },
  });

  const generateMutation = useMutation({
    mutationFn: () => generatePlannedOrders(),
    onSuccess: () => {
      setTimeout(() => {
        qc.invalidateQueries({ queryKey: ["planned-orders"] });
        qc.invalidateQueries({ queryKey: ["planned-orders-summary"] });
      }, 3000);
    },
  });

  const summary = summaryQ.data;
  const orders = ordersQ.data;

  return (
    <div className="space-y-4">
      {/* Info Banner */}
      <div className="text-xs text-amber-700 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded px-3 py-2 mb-3">
        <span className="font-semibold">ℹ System-generated proposals</span> — these are NOT purchase orders placed with suppliers. Approve = ready for release to procurement. See <strong>Open POs</strong> panel for orders already in transit.
      </div>

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="font-semibold text-base">Planned Orders</h3>
          <p className="text-xs text-muted-foreground mt-0.5">
            Time-phased order recommendations from the MRP engine.{" "}
            {summary?.generated_at && (
              <span>Last generated: {new Date(summary.generated_at).toLocaleString()}</span>
            )}
          </p>
        </div>
        <button
          onClick={() => generateMutation.mutate()}
          disabled={generateMutation.isPending}
          className="rounded-md bg-primary px-3 py-1.5 text-xs text-primary-foreground font-medium hover:bg-primary/90 disabled:opacity-50"
        >
          {generateMutation.isPending ? "Generating..." : "Generate"}
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          {
            label: "Proposed",
            value: summary?.status_counts?.proposed?.toLocaleString() ?? "—",
            sub: formatCurrency(summary?.total_proposed_value_usd ?? null),
            warn: false,
          },
          {
            label: "Past Due",
            value: summary?.past_due_proposed_count?.toLocaleString() ?? "—",
            sub: "need action",
            warn: (summary?.past_due_proposed_count ?? 0) > 0,
          },
          {
            label: "Approved",
            value: summary?.status_counts?.approved?.toLocaleString() ?? "—",
            sub: formatCurrency(summary?.total_approved_value_usd ?? null),
            warn: false,
          },
          {
            label: "Low Confidence",
            value: summary?.low_confidence_count?.toLocaleString() ?? "—",
            sub: `avg ${summary?.avg_confidence_score != null ? (summary.avg_confidence_score * 100).toFixed(0) + "%" : "—"}`,
            warn: (summary?.low_confidence_count ?? 0) > 0,
          },
        ].map((kpi) => (
          <div
            key={kpi.label}
            className={`rounded-lg border p-3 ${kpi.warn ? "border-amber-400/50 bg-amber-50/50 dark:bg-amber-900/10" : "bg-card"}`}
          >
            <p className="text-xs text-muted-foreground">{kpi.label}</p>
            <p className={`text-xl font-semibold mt-1 ${kpi.warn ? "text-amber-600 dark:text-amber-400" : ""}`}>
              {kpi.value}
            </p>
            <p className="text-xs text-muted-foreground mt-0.5">{kpi.sub}</p>
          </div>
        ))}
      </div>

      {/* Confidence Score Legend */}
      <div className="text-xs text-muted-foreground p-2 rounded bg-muted/30 border">
        <span className="font-medium text-foreground">Confidence Score: </span>
        <span className="text-green-600">● High ≥ 0.8</span> · <span className="text-amber-600">● Medium 0.5–0.79</span> · <span className="text-red-600">● Low &lt; 0.5</span>
        <span className="ml-2 text-muted-foreground">— Based on forecast accuracy + lead time stability</span>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-2 items-center">
        <input
          className="rounded-md border bg-background px-2 py-1 text-xs w-32"
          placeholder="Item No"
          value={itemFilter}
          onChange={(e) => setItemFilter(e.target.value)}
        />
        <input
          className="rounded-md border bg-background px-2 py-1 text-xs w-32"
          placeholder="Location"
          value={locFilter}
          onChange={(e) => setLocFilter(e.target.value)}
        />
        <select
          className="rounded-md border bg-background px-2 py-1 text-xs"
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
        >
          <option value="proposed,approved">Proposed + Approved</option>
          <option value="proposed">Proposed only</option>
          <option value="approved">Approved only</option>
          <option value="released">Released</option>
          <option value="rejected,cancelled">Rejected / Cancelled</option>
        </select>
        <label className="flex items-center gap-1 text-xs text-muted-foreground">
          <input
            type="checkbox"
            checked={pastDueOnly}
            onChange={(e) => setPastDueOnly(e.target.checked)}
          />
          Past-Due Only
        </label>
      </div>

      {/* Orders Table */}
      {ordersQ.isLoading ? (
        <div className="text-xs text-muted-foreground py-4 text-center">Loading...</div>
      ) : ordersQ.isError ? (
        <div className="text-xs text-red-600 py-4 text-center">Failed to load planned orders.</div>
      ) : !orders?.items?.length ? (
        <EmptyState
          icon={CheckSquare}
          title="No planned orders generated"
          description="Planned orders are system-generated replenishment proposals created when projected inventory falls below the reorder point within the lead time window. Each order has a confidence score based on data quality and recommends a quantity based on EOQ."
          steps={[
            { label: "Generate production forecasts first", command: "make forecast-generate" },
            { label: "Compute replenishment plan", command: "make replen-plan-compute" },
            { label: "Generate planned orders", command: "make planned-orders-generate" },
          ]}
        />
      ) : (
        <div className="rounded-lg border overflow-auto">
          <table className="w-full text-xs">
            <thead className="bg-muted/50">
              <tr>
                {[
                  { label: "Item" },
                  { label: "Loc" },
                  { label: "Supplier" },
                  { label: "Rec. Qty" },
                  { label: "Value" },
                  { label: "Order By", title: "Latest date to place this order to meet projected demand. Missing this date puts you at stockout risk." },
                  { label: "LT", title: "Lead time in days from order placement to receipt." },
                  { label: "Confidence" },
                  { label: "Status" },
                  { label: "Actions" },
                ].map((h) => (
                  <th key={h.label} title={h.title} className="px-3 py-2 text-left font-medium text-muted-foreground whitespace-nowrap">
                    {h.label}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y">
              {orders.items.map((order: PlannedOrder) => {
                const conf = confidenceLabel(order.confidence_score);
                const isPastDue = order.is_past_due;
                return (
                  <tr key={order.id} className={`hover:bg-muted/30 ${isPastDue ? "bg-red-50/30 dark:bg-red-900/10" : ""}`}>
                    <td className="px-3 py-2 font-mono">{order.item_no}</td>
                    <td className="px-3 py-2">{order.loc}</td>
                    <td className="px-3 py-2 text-muted-foreground">
                      {order.supplier_name ?? order.supplier_id ?? "—"}
                    </td>
                    <td className="px-3 py-2 font-semibold">{order.recommended_qty?.toLocaleString()}</td>
                    <td className="px-3 py-2">{formatCurrency(order.order_value)}</td>
                    <td className={`px-3 py-2 whitespace-nowrap ${isPastDue ? "text-red-600 dark:text-red-400 font-semibold" : ""}`}>
                      {formatDate(order.order_by_date)}
                      {isPastDue && " ⚠"}
                    </td>
                    <td className="px-3 py-2">{order.lead_time_days}d</td>
                    <td className={`px-3 py-2 ${conf.cls}`}>{conf.label}</td>
                    <td className="px-3 py-2">
                      <span className={`inline-block rounded-full px-2 py-0.5 text-xs font-medium ${
                        order.status === "proposed" ? "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300"
                        : order.status === "approved" ? "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300"
                        : order.status === "released" ? "bg-cyan-100 text-cyan-700"
                        : "bg-muted text-muted-foreground"
                      }`}>
                        {order.status}
                      </span>
                    </td>
                    <td className="px-3 py-2">
                      {order.status === "proposed" && (
                        <div className="flex gap-1">
                          <button
                            onClick={() => approveMutation.mutate({ id: order.id, approvedBy: "planner" })}
                            disabled={approveMutation.isPending}
                            className="rounded bg-emerald-600 px-2 py-0.5 text-white text-xs hover:bg-emerald-700 disabled:opacity-50"
                          >
                            Approve
                          </button>
                          <button
                            onClick={() => { setRejectModalId(order.id); setRejectReason(""); }}
                            className="rounded bg-red-600 px-2 py-0.5 text-white text-xs hover:bg-red-700"
                          >
                            Reject
                          </button>
                        </div>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Reject Modal */}
      {rejectModalId !== null && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="bg-card rounded-lg border p-4 shadow-lg w-80">
            <h4 className="font-semibold text-sm mb-2">Reject Order #{rejectModalId}</h4>
            <textarea
              className="w-full rounded border bg-background p-2 text-xs h-20 resize-none"
              placeholder="Rejection reason (required)"
              value={rejectReason}
              onChange={(e) => setRejectReason(e.target.value)}
            />
            <div className="flex gap-2 mt-3 justify-end">
              <button
                onClick={() => setRejectModalId(null)}
                className="rounded border px-3 py-1 text-xs hover:bg-muted"
              >
                Cancel
              </button>
              <button
                onClick={() => rejectMutation.mutate({ id: rejectModalId!, reason: rejectReason })}
                disabled={!rejectReason.trim() || rejectMutation.isPending}
                className="rounded bg-red-600 px-3 py-1 text-xs text-white hover:bg-red-700 disabled:opacity-50"
              >
                Confirm Reject
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
