-- IPAIfeature1: AI Planning Agent — insight storage tables
-- Run: psql $DATABASE_URL -f sql/027_create_ai_insights.sql

-- ---------------------------------------------------------------------------
-- ai_insights
-- Structured exception records written by the AI Planning Agent.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_insights (
    insight_id              SERIAL PRIMARY KEY,
    insight_type            VARCHAR(80) NOT NULL,
    severity                VARCHAR(20) NOT NULL CHECK (severity IN ('critical','high','medium','low')),

    -- DFU identity
    item_no                 TEXT NOT NULL,
    loc                     TEXT NOT NULL,
    abc_vol                 TEXT,
    cluster_assignment      TEXT,

    -- AI-generated content
    summary                 TEXT NOT NULL,
    recommendation          TEXT NOT NULL,
    reasoning               TEXT,

    -- Financial impact
    financial_impact_estimate  NUMERIC(15,2),

    -- Snapshot metrics at insight creation time
    dos                     NUMERIC(10,2),
    total_lt_days           INTEGER,
    champion_wape           NUMERIC(8,4),
    forecast_bias_pct       NUMERIC(8,4),
    current_policy_id       TEXT,
    eoq_effective           NUMERIC(12,2),

    -- Workflow status
    status                  VARCHAR(20) NOT NULL DEFAULT 'open'
                                CHECK (status IN ('open','acknowledged','resolved')),
    acknowledged_at         TIMESTAMPTZ,
    resolved_at             TIMESTAMPTZ,

    -- Provenance
    model_version           TEXT,
    scan_run_id             TEXT,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for UI list and DFU drill-in
CREATE INDEX IF NOT EXISTS idx_ai_insights_status_severity
    ON ai_insights (status, severity, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_insights_item_loc
    ON ai_insights (item_no, loc);

CREATE INDEX IF NOT EXISTS idx_ai_insights_scan_run
    ON ai_insights (scan_run_id);

CREATE INDEX IF NOT EXISTS idx_ai_insights_type
    ON ai_insights (insight_type);

-- ---------------------------------------------------------------------------
-- ai_planning_memos
-- Narrative planning memos generated by the AI agent (portfolio or DFU scope).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_planning_memos (
    memo_id         SERIAL PRIMARY KEY,
    period          DATE NOT NULL,
    scope           VARCHAR(20) NOT NULL CHECK (scope IN ('portfolio','dfu')),
    item_no         TEXT,
    loc             TEXT,
    narrative_text  TEXT NOT NULL,
    content_json    JSONB,
    model_version   TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_memos_period_scope
    ON ai_planning_memos (period DESC, scope);

CREATE INDEX IF NOT EXISTS idx_ai_memos_dfu
    ON ai_planning_memos (item_no, loc, period DESC)
    WHERE scope = 'dfu';
